DROP INDEX IF EXISTS FUNKMASTEN_POINT_INDEX;
DROP INDEX IF EXISTS FUNKMASTEN_FID_INDEX;
DROP INDEX IF EXISTS FUNKMASTEN_TYPE_INDEX;
DROP TABLE IF EXISTS FUNKMASTEN;
DROP TYPE IF EXISTS FUNKMASTEN_TYPE;

CREATE TYPE FUNKMASTEN_TYPE AS ENUM ('Mobilfunk', 'Sonstige Funkanlage');

CREATE TABLE FUNKMASTEN (
	fid integer,
	lon double precision,
	lat double precision,
	point geometry(POINT, 4326),
	type FUNKMASTEN_TYPE);

COPY
	FUNKMASTEN (
		fid,
		lon,
		lat,
		type
	)
FROM
	:FUNKMASTEN_INPUT
	DELIMITER ','
	CSV
		HEADER;

UPDATE FUNKMASTEN SET point = ST_SetSRID(ST_MakePoint(lon, lat), 4326);

CREATE INDEX FUNKMASTEN_POINT_INDEX ON FUNKMASTEN USING GIST(point);
CREATE INDEX FUNKMASTEN_FID_INDEX ON FUNKMASTEN (fid);
CREATE INDEX FUNKMASTEN_TYPE_INDEX ON FUNKMASTEN (type);